### ISSUE TITLE
Disabled power control become CRITICAL

### ISSUE THREAD

**Issue by hpcitdude** [bb-Ricardo/check_redfish#105]
Hi,

We had this in the older versions also. I tested on 1.5 just now and can see the same. We have 4 node enclosuers from Gigabyte where we can check the power status. The chassis is supplying power for the 4 nodes. If we are checking the nodes themselves we see a CRITICAL alert for the power check like:

[CRITICAL]: Chassis Power Control (status: CRITICAL/Disabled) current consumption: 597W

So in our install packages we have created a patch to fix this. Just set state to OK if power control is Disabled.  Request that you have a look at it and implement similar thing?

```
--- /usr/local/nagios/plugins/check_redfish/cr_module/power.py    2022-09-22 14:25:19.618392000 +0200
+++ power.py    2022-09-22 15:42:04.388101000 +0200
@@ -210,6 +210,8 @@
             power_control_status = get_status_data(grab(power_control, "Status"))
             status = power_control_status.get("Health")
             state = power_control_status.get("State")
+            if "Disabled" == state:
+                status = "OK"
             name = power_control.get("Name")
             reading = power_control.get("PowerConsumedWatts")
```

**Comment by bb-Ricardo** [comment]
Hi,

Would you be able to provide me with an redfish Mock of that server?

Then I could add it to my unit test environment and cover this case as well.

**Comment by hpcitdude** [comment]
Hi Ricardo,

Sure, I just sent you an email with a mockup taken for one of our blades.

**Comment by bb-Ricardo** [comment]
Awesome, thank you very much. Will add it.

Not sure how fast I will be able to add/fix this.

**Comment by bb-Ricardo** [comment]
Hey, I fixed it in `next-release` branch. Can you try it out please?
Thank you
