### ISSUE TITLE
Virtual Machine did not assigned to devices

### ISSUE THREAD

**Issue by dauongdia2525** [bb-Ricardo/check_redfish#106]
Hi Ricado, fristly i really thanks for your attribute, and i'm using it,
But I have a little bit problem related to Virtual Machines, its dit not auto-assign to devices,
I'm getting data from Vcenter via netbox-sync
Could you help me?
![Capture](https://user-images.githubusercontent.com/64430144/223613879-c2b366be-0437-48e9-8840-2b4cc80ab346.PNG)

**Comment by bb-Ricardo** [comment]
Hi,

Just wondering, which version of netbox-sync are you using? You can run it with `-h` and then you should see it.

**Comment by bb-Ricardo** [comment]
Also just realizing that this is the incorrect repository. Can you reopen this in netbox-sync?

Thank you.

**Comment by dauongdia2525** [comment]
Oh really sorry Ricado, i just updated latest version from dev branch and it's worked. Thanks for touch supports
