### ISSUE TITLE
ALREADY IN INVENTORY message in --nic

### ISSUE THREAD

**Issue by lgmu** [bb-Ricardo/check_redfish#109]
### Discussed in https://github.com/bb-Ricardo/check_redfish/discussions/107

<div type='discussions-op-text'>

<sup>Originally posted by **lgmu** March 10, 2023</sup>
Hi,

I have a quick question regarding this:
 https://github.com/bb-Ricardo/check_redfish/blob/main/cr_module/nic.py#L141
 
A customer of us uses the --nic mode on a Dell Inc. PowerEdge C6420

We get the following output:
ALREADY in INVENTORY: NIC.Mezzanine.3-1
ALREADY in INVENTORY: NIC.Mezzanine.3-1
ALREADY in INVENTORY: NIC.Mezzanine.3-1
ALREADY in INVENTORY: NIC.Mezzanine.3-2
ALREADY in INVENTORY: NIC.Mezzanine.3-2
ALREADY in INVENTORY: NIC.Mezzanine.3-2
[OK]: All network adapter (3) and ports (5) are in good condition

Is the "ALREADY in INVENTORY" really neccessary on stdout? Maybe it could only be printed in verbose. Or is this something they can avoid by configuring the device itself in a different way?</div>

**Comment by bb-Ricardo** [comment]
Hi, this means that these items are not added to the inventory as they use same ID for the same subsystem. Of course this message can be omitted but then you would never know this is data missing in the inventory.

**Comment by lgmu** [comment]
Thanks for your feedback, I'll ask them to check their configuration

**Comment by SirScruffy** [comment]
Hi,

we use check_redfish very intensive to inventory our servers, since the update to version 1.5.0 we have a similar problem with the generated JSONs on some servers. The beginning of the '--inventory --all' response starts with 'ALREADY in INVENTORY: NIC.Integrated.1' which is not valid JSON syntax and leads to problems with subsequent parsing attempts. It would be annoying if the JSON processing fails on servers that have a 4 port NIC.

Thanks for the great tool.

Many greetings,
Scruffy

**Comment by SirScruffy** [comment]
Hi, thanks for the quick reply!
I can send you an anonymized mockup of the server. 
Where should I send it to?

**Comment by bb-Ricardo** [comment]
That would be amazing. You can find my mail address in the upper part of check_redish.py

Thank you

**Comment by SirScruffy** [comment]
Hi,
is there anything new on the problem?

Cheers,
Scruffy

**Comment by bb-Ricardo** [comment]
Hi, currently not. There is alot going on at the moment.

Maybe I find some time tonight.

**Comment by bb-Ricardo** [comment]
Hey @SirScruffy,

I just pushed a commit to `next-release` branch-. can you check if this works better now?

Thank you

**Comment by SirScruffy** [comment]
Hi @bb-Ricardo,

I just tested it and the JSON looks fine. Thank you for very much.

Cheers,
Scruffy
