### ISSUE TITLE
Mode --firmware also checks --storage -> Request error: No array controller data returned for API URL '/redfish/v1/Systems/1//SmartStorage/ArrayControllers?$expand=.'

### ISSUE THREAD

**Issue by lgmu** [bb-Ricardo/check_redfish#112]
Hi,
we have a problem when using --firmware, because it also tries to check the storage and array controllers

https://github.com/bb-Ricardo/check_redfish/blob/next-release/cr_module/firmware.py#L128

The --storage doesn't work on the HPE ProLiant BL460c Gen9 with BIOS: I36 v2.74 (07/21/2019):
[UNKNOWN]: No storage controller and disk drive data found in system
[UNKNOWN]: Request error: No array controller data returned for API URL '/redfish/v1/Systems/1//SmartStorage/ArrayControllers?$expand=.'

This seems to be a known bug of that BIOS, but they can't upgrade their BIOS right now, so we just removed the --storage, but we still get the UNKNOWN on the --firmware Mode because of Line mentioned above. 

Shouldn't it be the other way around, only checking the Firmware of the Drives when also using --storage or --all?

Thanks

**Comment by bb-Ricardo** [comment]
Hi,

this is indeed a bug. We currently have the same issue/behaviour and hope to fox this soon.

**Comment by lgmu** [comment]
Alright thanks, as a temp fix I'll just set it to "True" locally

**Comment by lgmu** [comment]
Any update?
Thanks

**Comment by bb-Ricardo** [comment]
Hi @lgmu,

finally got some time to look into it. I pushed a commit to 'next-release' branch. Can you have a look and test it?

thank you very much.

**Comment by bb-Ricardo** [comment]
Hi @lgmu: any chance of testing this commit?

**Comment by lgmu** [comment]
Hi, sorry I was on vacation, I'll try to find time later today and give you feedback!

**Comment by lgmu** [comment]
Seems to be working fine now, thanks for the fix :)

**Comment by bb-Ricardo** [comment]
Hey @lgmu,

no need to be sorry for well deserved vacations. Thank you very much for testing it and the feedback, highly appreciated.
