### ISSUE TITLE
Duplicate Power supplies reported with HPE Apollo 4510 Gen10

### ISSUE THREAD

**Issue by pdenessen** [bb-Ricardo/check_redfish#114]
When I run the script on a HPE Apollo 4510 Gen10 then I get the 4 power supplies listed twice which results in duplicate errors when using the file by syncing with the netbx-sync script.

ILO firmware 2.14 dd 11 Feb 2020

Command used: 
 python3 check_redfish.py -H <ip_address> -u <username> -p <password> --power --inventory > <output_filename.json>

**Comment by bb-Ricardo** [comment]
Hi @pdenessen,

That is really interesting. I haven't seen this behavior before. I don't have a server of this kind available but would highly appreciated to add a mockup of this kind to my test environment to cover this type as well.
Would you mind using this https://github.com/DMTF/Redfish-Mockup-Creator and sending me a mockup via email. I know it might contain sensitive data and I highly encourage you to vet it from before sinding it over. you can find my mail address here: https://github.com/bb-Ricardo/check_redfish/blob/d5c4ee96d24266c6b172c31758682c187a2be8ad/check_redfish.py#L21

Would that be possible?

Thank you.
