### ISSUE TITLE
Two entries "UNKNOWN" (storage controllers and Network Adapters)

### ISSUE THREAD

**Issue by Djdodo666** [bb-Ricardo/check_redfish#124]
Hi, if I run the command with "--all", I get two UNKOWN-entries.
The one for the storage controller (which is correct as ESXi is running fron SD-Card) and one for network adapters.

[UNKNOWN]: Request error: No network adapter or interface data returned for API URL '/redfish/v1/Systems/System.Embedded.1/NetworkInterfaces'

BUT:
[OK]: All network adapter (0) and ports (8) are in good condition

How can I go around this to avoid alarms?

**Comment by Djdodo666** [comment]
Weird.
The UNKNOWN of the network-adapters stays the same, UNKNOWN of storage adapters is gone.
Here is the system info:
![image](https://github.com/bb-Ricardo/check_redfish/assets/37834772/38ba5e93-b98b-4774-8599-dd98048e1e53)

**Comment by Djdodo666** [comment]
Is there any way to add these two adapter models to the check?

**Comment by bb-Ricardo** [comment]
This looks like a Dell iDRAC. I currently don't know why the Network adapters don't show up.

Can you create a Mockup with the Redfish Mockup creator and send result via email? Then I could add it to my test suit and find out why the network adapters are missing.

**Comment by bb-Ricardo** [comment]
You mentioned the issue has been resolved via an iDRAC firmware update. Therefore will close this issue.
