### ISSUE TITLE
Cisco C220 M5SX

### ISSUE THREAD

**Issue by MisterMountain** [bb-Ricardo/check_redfish#136]
Hello,

we have an Cisco C220 M5SX.
While trying to check the nics of the cisco server we get an error that no network interfaces are found:
./check_redfish/check_redfish.py --all -H hostname -u admin -p redacted
[UNKNOWN]: Request error: No network adapter or interface data returned for API URL '/redfish/v1/Systems/serial_number/NetworkInterfaces'

However, by manual curling we found that there are EthernetInterfaces existent:
`curl --insecure -H "Content-Type: application/json" hostname/redfish/v1/Systems/serial_number/EthernetInterfaces -u "admin:redacted"`
```json
{
	"@odata.id":	"/redfish/v1/Systems/serial_number/EthernetInterfaces",
	"@odata.type":	"#EthernetInterfaceCollection.EthernetInterfaceCollection",
	"@odata.context":	"/redfish/v1/$metadata#EthernetInterfaceCollection.EthernetInterfaceCollection",
	"Name":	"Ethernet Interfaces Collection",
	"Members":	[{
			"@odata.id":	"/redfish/v1/Systems/serial_number/EthernetInterfaces/L.2"
		}, {
			"@odata.id":	"/redfish/v1/Systems/serial_number/EthernetInterfaces/L.1"
		}],
	"Members@odata.count":	2,
	"Description":	"Collection of EthernetInterfaces for this System"
}
```

Do you know about any way to resolve this?

**Comment by bb-Ricardo** [comment]
Hi,

Which version of the Script are you using? And which CIMC Version  are you using?

If you are using the latest versions would you be able to provide a MockUp as described here: https://github.com/DMTF/Redfish-Mockup-Creator : [usage](https://github.com/DMTF/Redfish-Mockup-Creator/blob/main/README.md#usage)

**Comment by Azmodeszer** [comment]
Running CIMC/BMC version: 4.1(3d)

We are using netways-plugins-redfish (1.7.3-1.bookworm).

**Comment by bb-Ricardo** [comment]
Hi, then a Mockup would be very helpful. Thank you

**Comment by MisterMountain** [comment]
Hello, we created a mockup - here you go: https://transfer.netways.de/index.php/s/pqsf5abP7Z4f4sa
Hope this helps:)

**Comment by bb-Ricardo** [comment]
Thank you for the mockup.

I had a look at the mockup data and there is basically no network information present.

plugin output looks like this:
```
[UNKNOWN]: Request error: No network adapter or interface data returned for API URL '/redfish/v1/Systems/SERIAL/NetworkInterfaces'
[OK]: Port L.2 (type: None, speed: None, autoneg: None, duplex: None) link: None
[OK]: Port L.1 (type: None, speed: None, autoneg: None, duplex: None) link: None
```

the mockup shows following resources:
> redfish/v1/Systems/SERIAL/NetworkInterfaces/index.json
```json
{
    "@odata.id": "/redfish/v1/Systems/SERIAL/NetworkInterfaces",
    "@odata.type": "#NetworkInterfaceCollection.NetworkInterfaceCollection",
    "@odata.context": "/redfish/v1/$metadata#NetworkInterfaceCollection.NetworkInterfaceCollection",
    "Description": "Collection of NetworkInterface resource instances for this system",
    "Name": "NetworkInterface Collection",
    "Members": [],
    "Members@odata.count": 0
}
```

> redfish/v1/Systems/Serial/EthernetInterfaces/L.1/index.json
```json
{
    "@odata.id": "/redfish/v1/Systems/Serial/EthernetInterfaces/L.1",
    "@odata.type": "#EthernetInterface.v1_4_1.EthernetInterface",
    "@odata.context": "/redfish/v1/$metadata#EthernetInterface.EthernetInterface",
    "Links": {
        "Chassis": {
            "@odata.id": "/redfish/v1/Chassis/1"
        }
    },
    "Id": "L.1",
    "Name": "Ethernet Interface",
    "MACAddress": "aa:bb:cc:ee:ff:11",
    "PermanentMACAddress": "aa:bb:cc:ee:ff:11",
    "Description": "Network Interface"
}
```

> redfish/v1/Chassis/1/NetworkAdapters/index.json
```json
{
    "@odata.id": "/redfish/v1/Chassis/1/NetworkAdapters",
    "@odata.type": "#NetworkAdapterCollection.NetworkAdapterCollection",
    "@odata.context": "/redfish/v1/$metadata#NetworkAdapterCollection.NetworkAdapterCollection",
    "Description": "Collection of NetworkAdapter resource instances for this system",
    "Name": "NetworkAdapter Collection",
    "Members": [],
    "Members@odata.count": 0
}
```

I guess this is the reason why you don't see much infos.

**Comment by MisterMountain** [comment]
Seems like that cisco server is not very talkative

**Comment by bb-Ricardo** [comment]
Hi, indeed, there are not many details. Can I close this issue?
