### ISSUE TITLE
Problems with iDRAC9 15G

### ISSUE THREAD

**Issue by ajoergensen** [bb-Ricardo/check_redfish#14]
We have just received some servers equipped with iDRAC 15G with firmware version 4.x.x.x

These checks work:
--bmc
--cpu
--memory
--info
--firmware
--mel
--sel

These fail:
--power
--temp
--storage (returns UNKNOWN)
--nic

All (except storage) fails with "The read operation timed out" - And if I query the URL directly it returns http 503 - But I am uncertain if the problem is within iDRAC or check_icinga - which is why I'm opening this issue before contacting Dell support.

I can provide mockup data if needed.

**Comment by bb-Ricardo** [comment]
Hi,

You could try using `-v` option and setting the timeout higher `--timeout 30`. Then you should be able to see what's going on.

If you still get a "503" then I would contact DELL support and ask for their help.

**Comment by ajoergensen** [comment]
I just noticed something, on both temp and power, the failing URL looks like this: `/redfish/v1/Chassis/Enclosure.Internal.0-0/Thermal` (or Power) but before it returns what looks to be all the expected data.

For storage, the result is `[UNKNOWN]: No array controller data returned for API URL '/redfish/v1/Systems/System.Embedded.1/Storage/CPU.1'` - but when running with -v I see information about some (or perhaps) all storage devices returned.

My offer to provide a data dump stands :)

**Comment by bb-Ricardo** [comment]
😄 I gladly take your offer.

Thank you

**Comment by bb-Ricardo** [comment]
@ajoergensen ping

**Comment by bb-Ricardo** [comment]
I added some changes to the plugin. can you check out "next-release" and see if it works?

Thank you

**Comment by ajoergensen** [comment]
Hi,

it seems to be working, I'm able to run it by hand and get the output I expect. I'll test it in Icinga shortly.

mvh
Allan

**Comment by ajoergensen** [comment]
It works as expected.

Thank you,
Allan

**Comment by bb-Ricardo** [comment]
Thank you for testing.

Will close this one.
