### ISSUE TITLE
extend plugin output from --storage --detailed

### ISSUE THREAD

**Issue by lpohle** [bb-Ricardo/check_redfish#140]
hello, 
is it possible to extend plugin output from --storage --detailed according to the following example 

[OK]: Physical Drive (1I:3:4) 3200GB (MO003200PZWSK / SSD / SAS / Medialife 100% / Predicted Failure None / Status Enabled / 3506 hrs in operation) Status: OK
[OK]: Physical Drive (1I:3:3) 3200GB (MO003200PZWSK / SSD / SAS / Medialife 100% / Predicted Failure None / Status Enabled / 3506 hrs in operation) Status: OK

To do this, only the status text must be extended by storage.py for discs in the following way:
            status_text = f"Physical Drive ({pd_inventory.location}) {size}GB " \
                          f"({pd_inventory.model} / {pd_inventory.type} / {pd_inventory.interface_type} / Medialife {pd_inventory.predicted_media_life_left_percent}% / Predicted Failure {pd_inventory.failure_predicted} / " \
                          f"Status {pd_inventory.operation_status} / {pd_inventory.power_on_hours} Std in Betrieb) " \
                          f"Status: {pd_inventory.health_status}{drive_status_reasons}"

**Comment by bb-Ricardo** [comment]
Hi @lpohle,

thank you for this Idea. I have a look in how the output can be improved.

**Comment by bb-Ricardo** [comment]
Ho @lpohle,

I improved the output and included all suggested fields. If `pd_inventory.failure_predicted` is false, it will not be added. Only if `pd_inventory.failure_predicted` is set to `true`.

can you test the `next-release` branch and check the result?

thank you.
