### ISSUE TITLE
host down when underscore in hostname

### ISSUE THREAD

**Issue by scheurer13** [bb-Ricardo/check_redfish#19]
Hello,

on testing this check_script we run in to an error when the hostname conatins an underscore.
So if the hostname is "server_adm" the status is Down. With the ip or change dns/hosts to "serveradm" the check script runs fine.

`
/usr/lib/nagios/plugins # check_redfish/check_redfish.py -H 10.192.1.187 -f /etc/icinga2/check_redfish_icinga.login --temp
[OK]: All temp sensors (4) are in good condition|'temp_CPU1_Temp'=58.0;;98 'temp_CPU2_Temp'=58.0;;98 'temp_System_Board_Inlet_Temp'=23.0;38;42 'temp_System_Board_Exhaust_Temp'=33.0;75;80
/usr/lib/nagios/plugins # check_redfish/check_redfish.py -H sxs20027_adm -f /etc/icinga2/check_redfish_icinga.login --temp
[CRITICAL]: Host 'sxs20027_adm' down or unreachable.
/usr/lib/nagios/plugins # check_redfish/check_redfish.py -H sxs20027adm -f /etc/icinga2/check_redfish_icinga.login --temp
[OK]: All temp sensors (4) are in good condition|'temp_CPU1_Temp'=55.0;;98 'temp_CPU2_Temp'=54.0;;98 'temp_System_Board_Inlet_Temp'=23.0;38;42 'temp_System_Board_Exhaust_Temp'=33.0;75;80
`

**Comment by bb-Ricardo** [comment]
Mmhh. My first suggestion would be this: https://stackoverflow.com/a/14622263

It is still difficult to use underscores in host names.

I will have a look into it but most likely it originates in the request python lib.
