### ISSUE TITLE
Base.1.5.QueryNotSupportedOnResource Error since Firmware-Upgrade on Fujitsu Server

### ISSUE THREAD

**Issue by robse030** [bb-Ricardo/check_redfish#20]
Hi, since the last irmc Firmware Upgrade to Version 2.63P on my Fujitsu RX2540 M4 i got these error when i query nic or status by redfish.

**Comment by bb-Ricardo** [comment]
Hi,

Could you post a command output with the "-v" option switched on? You might want to remove serial numbers from the output. This way I might could figure out what goes wrong.

Thank you.

**Comment by robse030** [comment]
Hi Ricardo,

here is the output:

`2020-07-15 22:35:14,890 - DEBUG: HTTP REQUEST: GET
        PATH: /redfish/v1/Chassis
        BODY: None
2020-07-15 22:35:14,890 - INFO: Attempt 1 of /redfish/v1/Chassis
2020-07-15 22:35:15,127 - INFO: Response Time to /redfish/v1/Chassis: 0.07474811600059184 seconds.
2020-07-15 22:35:15,128 - DEBUG: HTTP RESPONSE for /redfish/v1/Chassis:
Code: 200 OK
Headers:
        Access-Control-Allow-Origin: *
        OData-Version: 4.0
        Cache-Control: no-cache
        Link: </redfish/v1/JsonSchemas/ChassisCollection>; rel=describedby
        Allow: GET
        ETag: 1594839099
        Date: Wed, 15 Jul 2020 20:35:14 GMT
        Server: iRMC S5 Webserver
        X-Frame-Options: DENY
        X-XSS-Protection: 1; mode=block
        X-Content-Type-Options: nosniff
        Referrer-Policy: no-referrer
        Strict-Transport-Security: max-age=0 ; includeSubDomains
        Expires: Tue, 14 Jul 2020 20:35:14 GMT
        Content-Length: 420
        Content-Type: application/json; charset=UTF-8

Body Response of /redfish/v1/Chassis: b'{\n  "@odata.id":"\\/redfish\\/v1\\/Chassis",\n  "@odata.type":"#ChassisCollection.ChassisCollection",\n  "Name":"Chassis Collection",\n  "Members":[\n    {\n      "@odata.id":"\\/redfish\\/v1\\/Chassis\\/0"\n    }\n  ],\n  "Members@odata.count":1,\n  "Oem":{\n  },\n  "@Redfish.Copyright":"Copyright 2014-2018 DMTF. For the full DMTF copyright policy, see http:\\/\\/www.dmtf.org\\/about\\/policies\\/copyright",\n  "@odata.etag":"1594839099"\n}'
{'@Redfish.Copyright': 'Copyright 2014-2018 DMTF. For the full DMTF copyright '
                       'policy, see '
                       'http://www.dmtf.org/about/policies/copyright',
 '@odata.etag': '1594839099',
 '@odata.id': '/redfish/v1/Chassis',
 '@odata.type': '#ChassisCollection.ChassisCollection',
 'Members': [{'@odata.id': '/redfish/v1/Chassis/0'}],
 'Members@odata.count': 1,
 'Name': 'Chassis Collection',
 'Oem': {}}
2020-07-15 22:35:15,131 - DEBUG: HTTP REQUEST: GET
        PATH: /redfish/v1/Managers
        BODY: None
2020-07-15 22:35:15,131 - INFO: Attempt 1 of /redfish/v1/Managers
2020-07-15 22:35:15,207 - INFO: Response Time to /redfish/v1/Managers: 0.07480389699958323 seconds.
2020-07-15 22:35:15,208 - DEBUG: HTTP RESPONSE for /redfish/v1/Managers:
Code: 200 OK
Headers:
        Access-Control-Allow-Origin: *
        OData-Version: 4.0
        Cache-Control: no-cache
        Link: </redfish/v1/JsonSchemas/ManagerCollection>; rel=describedby
        Allow: GET
        ETag: 1594839111
        Date: Wed, 15 Jul 2020 20:35:14 GMT
        Server: iRMC S5 Webserver
        X-Frame-Options: DENY
        X-XSS-Protection: 1; mode=block
        X-Content-Type-Options: nosniff
        Referrer-Policy: no-referrer
        Strict-Transport-Security: max-age=0 ; includeSubDomains
        Expires: Tue, 14 Jul 2020 20:35:14 GMT
        Content-Length: 425
        Content-Type: application/json; charset=UTF-8

Body Response of /redfish/v1/Managers: b'{\n  "@odata.id":"\\/redfish\\/v1\\/Managers",\n  "@odata.type":"#ManagerCollection.ManagerCollection",\n  "Name":"Manager Collection",\n  "Members@odata.count":1,\n  "Members":[\n    {\n      "@odata.id":"\\/redfish\\/v1\\/Managers\\/iRMC"\n    }\n  ],\n  "Oem":{\n  },\n  "@Redfish.Copyright":"Copyright 2014-2018 DMTF. For the full DMTF copyright policy, see http:\\/\\/www.dmtf.org\\/about\\/policies\\/copyright",\n  "@odata.etag":"1594839111"\n}'
{'@Redfish.Copyright': 'Copyright 2014-2018 DMTF. For the full DMTF copyright '
                       'policy, see '
                       'http://www.dmtf.org/about/policies/copyright',
 '@odata.etag': '1594839111',
 '@odata.id': '/redfish/v1/Managers',
 '@odata.type': '#ManagerCollection.ManagerCollection',
 'Members': [{'@odata.id': '/redfish/v1/Managers/iRMC'}],
 'Members@odata.count': 1,
 'Name': 'Manager Collection',
 'Oem': {}}
2020-07-15 22:35:15,210 - DEBUG: HTTP REQUEST: GET
        PATH: /redfish/v1/Systems
        BODY: None
2020-07-15 22:35:15,210 - INFO: Attempt 1 of /redfish/v1/Systems
2020-07-15 22:35:15,298 - INFO: Response Time to /redfish/v1/Systems: 0.0867750409997825 seconds.
2020-07-15 22:35:15,300 - DEBUG: HTTP RESPONSE for /redfish/v1/Systems:
Code: 200 OK
Headers:
        Access-Control-Allow-Origin: *
        OData-Version: 4.0
        Cache-Control: no-cache
        Link: </redfish/v1/JsonSchemas/ComputerSystemCollection>; rel=describedby
        Allow: GET
        ETag: 1594839102
        Date: Wed, 15 Jul 2020 20:35:14 GMT
        Server: iRMC S5 Webserver
        X-Frame-Options: DENY
        X-XSS-Protection: 1; mode=block
        X-Content-Type-Options: nosniff
        Referrer-Policy: no-referrer
        Strict-Transport-Security: max-age=0 ; includeSubDomains
        Expires: Tue, 14 Jul 2020 20:35:14 GMT
        Content-Length: 442
        Content-Type: application/json; charset=UTF-8

Body Response of /redfish/v1/Systems: b'{\n  "@odata.id":"\\/redfish\\/v1\\/Systems",\n  "@odata.type":"#ComputerSystemCollection.ComputerSystemCollection",\n  "Name":"Computer System Collection",\n  "Members":[\n    {\n      "@odata.id":"\\/redfish\\/v1\\/Systems\\/0"\n    }\n  ],\n  "Members@odata.count":1,\n  "Oem":{\n  },\n  "@Redfish.Copyright":"Copyright 2014-2018 DMTF. For the full DMTF copyright policy, see http:\\/\\/www.dmtf.org\\/about\\/policies\\/copyright",\n  "@odata.etag":"1594839102"\n}'
{'@Redfish.Copyright': 'Copyright 2014-2018 DMTF. For the full DMTF copyright '
                       'policy, see '
                       'http://www.dmtf.org/about/policies/copyright',
 '@odata.etag': '1594839102',
 '@odata.id': '/redfish/v1/Systems',
 '@odata.type': '#ComputerSystemCollection.ComputerSystemCollection',
 'Members': [{'@odata.id': '/redfish/v1/Systems/0'}],
 'Members@odata.count': 1,
 'Name': 'Computer System Collection',
 'Oem': {}}
2020-07-15 22:35:15,306 - DEBUG: HTTP REQUEST: GET
        PATH: /redfish/v1/Managers/iRMC?$expand=Members
        BODY: None
2020-07-15 22:35:15,307 - INFO: Attempt 1 of /redfish/v1/Managers/iRMC?$expand=Members
2020-07-15 22:35:15,397 - INFO: Response Time to /redfish/v1/Managers/iRMC?$expand=Members: 0.08830858300007094 seconds.
2020-07-15 22:35:15,398 - DEBUG: HTTP RESPONSE for /redfish/v1/Managers/iRMC?$expand=Members:
Code: 400 Bad Request
Headers:
        Access-Control-Allow-Origin: *
        OData-Version: 4.0
        Cache-Control: no-cache
        Date: Wed, 15 Jul 2020 20:35:14 GMT
        Server: iRMC S5 Webserver
        X-Frame-Options: DENY
        X-XSS-Protection: 1; mode=block
        X-Content-Type-Options: nosniff
        Referrer-Policy: no-referrer
        Strict-Transport-Security: max-age=0 ; includeSubDomains
        Expires: Tue, 14 Jul 2020 20:35:14 GMT
        Content-Length: 505
        Content-Type: application/json; charset=UTF-8

Body Response of /redfish/v1/Managers/iRMC?$expand=Members: b'{\n  "error":{\n    "@Message.ExtendedInfo":[\n      {\n        "@odata.type":"#Message.1_0_0.Message",\n        "MessageId":"Base.1.5.QueryNotSupportedOnResource",\n        "Message":"Querying is not supported on the requested resource.",\n        "Severity":"Warning",\n        "Resolution":"Remove the query parameters and resubmit the request if the operation failed."\n      }\n    ],\n    "code":"Base.1.5.QueryNotSupportedOnResource",\n    "message":"Querying is not supported on the requested resource."\n  }\n}'
2020-07-15 22:35:15,400 - DEBUG: HTTP REQUEST: GET
        PATH: /redfish/v1/
        BODY: None
2020-07-15 22:35:15,401 - INFO: Attempt 1 of /redfish/v1/
2020-07-15 22:35:15,558 - INFO: Response Time to /redfish/v1/: 0.036450829000386875 seconds.
2020-07-15 22:35:15,560 - DEBUG: HTTP RESPONSE for /redfish/v1/:
Code: 200 OK
Headers:
        Access-Control-Allow-Origin: *
        OData-Version: 4.0
        Cache-Control: no-cache
        Link: </redfish/v1/JsonSchemas/ServiceRoot.v1_4_2>; rel=describedby
        Link: </redfish/v1/JsonSchemas/FTSServiceRoot.v1_2_1>; rel=describedby
        Allow: GET
        ETag: 1594839099
        Date: Wed, 15 Jul 2020 20:35:14 GMT
        Server: iRMC S5 Webserver
        X-Frame-Options: DENY
        X-XSS-Protection: 1; mode=block
        X-Content-Type-Options: nosniff
        Referrer-Policy: no-referrer
        Strict-Transport-Security: max-age=0 ; includeSubDomains
        Expires: Tue, 14 Jul 2020 20:35:14 GMT
        Content-Length: 2149
        Content-Type: application/json; charset=UTF-8

Body Response of /redfish/v1/: b'{\n  "@odata.id":"\\/redfish\\/v1\\/",\n  "@odata.type":"#ServiceRoot.v1_4_2.ServiceRoot",\n  "Oem":{\n    "ts_fujitsu":{\n      "@odata.type":"#FTSServiceRoot.v1_2_1.FTSServiceRoot",\n      "FileDownload":{\n        "@odata.id":"\\/redfish\\/v1\\/Oem\\/ts_fujitsu\\/FileDownload"\n      },\n      "DumpDownload":{\n        "@odata.id":"\\/redfish\\/v1\\/Oem\\/ts_fujitsu\\/DumpDownload"\n      },\n      "CASConfiguration":{\n        "Enabled":false,\n        "DisplayLoginPage":false,\n        "ServerLoginUri":null,\n        "ServerLogoutUri":null\n      },\n      "AutoDiscoveryDescription":{\n        "ServerNodeInformation":{\n          "SlotNumber":255,\n          "Model":"PRIMERGY RX2540 M4",\n          "SerialNumber":""\n        },\n        "ChassisInformation":{\n          "Model":"PRIMERGY RX2540 M4",\n          "SerialNumber":"YM6D027650"\n        }\n      }\n    }\n  },\n  "Id":"RootService",\n  "Name":"Root Service",\n  "RedfishVersion":"1.8.0",\n  "UUID":"eb6bbb00-9fe5-4c1c-b5b9-64d35cca8604",\n  "Links":{\n    "Oem":{\n    },\n    "Sessions":{\n      "@odata.id":"\\/redfish\\/v1\\/SessionService\\/Sessions"\n    }\n  },\n  "Systems":{\n    "@odata.id":"\\/redfish\\/v1\\/Systems"\n  },\n  "Chassis":{\n    "@odata.id":"\\/redfish\\/v1\\/Chassis"\n  },\n  "Managers":{\n    "@odata.id":"\\/redfish\\/v1\\/Managers"\n  },\n  "Tasks":{\n    "@odata.id":"\\/redfish\\/v1\\/TaskService"\n  },\n  "SessionService":{\n    "@odata.id":"\\/redfish\\/v1\\/SessionService"\n  },\n  "AccountService":{\n    "@odata.id":"\\/redfish\\/v1\\/AccountService"\n  },\n  "EventService":{\n    "@odata.id":"\\/redfish\\/v1\\/EventService"\n  },\n  "Registries":{\n    "@odata.id":"\\/redfish\\/v1\\/Registries"\n  },\n  "JsonSchemas":{\n    "@odata.id":"\\/redfish\\/v1\\/JsonSchemas"\n  },\n  "ProtocolFeaturesSupported":{\n    "ExcerptQuery":false,\n    "SelectQuery":false,\n    "OnlyMemberQuery":false,\n    "FilterQuery":false,\n    "ExpandQuery":{\n      "ExpandAll":false,\n      "Levels":false,\n      "Links":false,\n      "MaxLevels":false,\n      "NoLinks":false\n    }\n  },\n  "@Redfish.Copyright":"Copyright 2014-2018 DMTF. For the full DMTF copyright policy, see http:\\/\\/www.dmtf.org\\/about\\/policies\\/copyright",\n  "@odata.etag":"1594839099"\n}'
2020-07-15 22:35:15,562 - DEBUG: HTTP REQUEST: POST
        PATH: /redfish/v1/SessionService/Sessions
        BODY: {"UserName": "admin", "Password": ""}
2020-07-15 22:35:15,563 - INFO: Attempt 1 of /redfish/v1/SessionService/Sessions
2020-07-15 22:35:16,047 - INFO: Response Time to /redfish/v1/SessionService/Sessions: 0.3516098529998999 seconds.
2020-07-15 22:35:16,048 - DEBUG: HTTP RESPONSE for /redfish/v1/SessionService/Sessions:
Code: 201 Created
Headers:
        Access-Control-Allow-Origin: *
        OData-Version: 4.0
        Cache-Control: no-cache
        ETag: 1594845315
        Location: /redfish/v1/SessionService/Sessions/15
        X-Auth-Token: usLZ3nrW31bjt/bi
        Date: Wed, 15 Jul 2020 20:35:15 GMT
        Server: iRMC S5 Webserver
        X-Frame-Options: DENY
        X-XSS-Protection: 1; mode=block
        X-Content-Type-Options: nosniff
        Referrer-Policy: no-referrer
        Strict-Transport-Security: max-age=0 ; includeSubDomains
        Expires: Tue, 14 Jul 2020 20:35:15 GMT
        Content-Length: 532
        Content-Type: application/json; charset=UTF-8

Body Response of /redfish/v1/SessionService/Sessions: b'{\n  "@odata.id":"\\/redfish\\/v1\\/SessionService\\/Sessions\\/15",\n  "@odata.type":"#Session.v1_0_3.Session",\n  "Id":"15",\n  "Name":"Session",\n  "UserName":"admin",\n  "Oem":{\n    "ts_fujitsu":{\n      "@odata.type":"#FTSSessionService.v1_3_1.FTSOemSession",\n      "RoleId":"Administrator",\n      "UseVideoRedirection":true,\n      "UseRemoteStorage":true\n    }\n  },\n  "@Redfish.Copyright":"Copyright 2014-2018 DMTF. For the full DMTF copyright policy, see http:\\/\\/www.dmtf.org\\/about\\/policies\\/copyright",\n  "@odata.etag":"1594845315"\n}'
2020-07-15 22:35:16,049 - INFO: {'@odata.id': '/redfish/v1/SessionService/Sessions/15', '@odata.type': '#Session.v1_0_3.Session', 'Id': '15', 'Name': 'Session', 'UserName': 'admin', 'Oem': {'ts_fujitsu': {'@odata.type': '#FTSSessionService.v1_3_1.FTSOemSession', 'RoleId': 'Administrator', 'UseVideoRedirection': True, 'UseRemoteStorage': True}}, '@Redfish.Copyright': 'Copyright 2014-2018 DMTF. For the full DMTF copyright policy, see http://www.dmtf.org/about/policies/copyright', '@odata.etag': '1594845315'}
2020-07-15 22:35:16,049 - INFO: Login returned code 201: {
  "@odata.id":"\/redfish\/v1\/SessionService\/Sessions\/15",
  "@odata.type":"#Session.v1_0_3.Session",
  "Id":"15",
  "Name":"Session",
  "UserName":"admin",
  "Oem":{
    "ts_fujitsu":{
      "@odata.type":"#FTSSessionService.v1_3_1.FTSOemSession",
      "RoleId":"Administrator",
      "UseVideoRedirection":true,
      "UseRemoteStorage":true
    }
  },
  "@Redfish.Copyright":"Copyright 2014-2018 DMTF. For the full DMTF copyright policy, see http:\/\/www.dmtf.org\/about\/policies\/copyright",
  "@odata.etag":"1594845315"
}
2020-07-15 22:35:16,051 - DEBUG: HTTP REQUEST: GET
        PATH: /redfish/v1/Managers/iRMC?$expand=Members
        BODY: None
2020-07-15 22:35:16,051 - INFO: Attempt 1 of /redfish/v1/Managers/iRMC?$expand=Members
2020-07-15 22:35:16,237 - INFO: Response Time to /redfish/v1/Managers/iRMC?$expand=Members: 0.18484539299970493 seconds.
2020-07-15 22:35:16,238 - DEBUG: HTTP RESPONSE for /redfish/v1/Managers/iRMC?$expand=Members:
Code: 400 Bad Request
Headers:
        Access-Control-Allow-Origin: *
        OData-Version: 4.0
        Cache-Control: no-cache
        Date: Wed, 15 Jul 2020 20:35:15 GMT
        Server: iRMC S5 Webserver
        X-Frame-Options: DENY
        X-XSS-Protection: 1; mode=block
        X-Content-Type-Options: nosniff
        Referrer-Policy: no-referrer
        Strict-Transport-Security: max-age=0 ; includeSubDomains
        Expires: Tue, 14 Jul 2020 20:35:15 GMT
        Content-Length: 505
        Content-Type: application/json; charset=UTF-8

Body Response of /redfish/v1/Managers/iRMC?$expand=Members: b'{\n  "error":{\n    "@Message.ExtendedInfo":[\n      {\n        "@odata.type":"#Message.1_0_0.Message",\n        "MessageId":"Base.1.5.QueryNotSupportedOnResource",\n        "Message":"Querying is not supported on the requested resource.",\n        "Severity":"Warning",\n        "Resolution":"Remove the query parameters and resubmit the request if the operation failed."\n      }\n    ],\n    "code":"Base.1.5.QueryNotSupportedOnResource",\n    "message":"Querying is not supported on the requested resource."\n  }\n}'
{'error': {'@Message.ExtendedInfo': [{'@odata.type': '#Message.1_0_0.Message',
                                      'Message': 'Querying is not supported on '
                                                 'the requested resource.',
                                      'MessageId': 'Base.1.5.QueryNotSupportedOnResource',
                                      'Resolution': 'Remove the query '
                                                    'parameters and resubmit '
                                                    'the request if the '
                                                    'operation failed.',
                                      'Severity': 'Warning'}],
           'code': 'Base.1.5.QueryNotSupportedOnResource',
           'message': 'Querying is not supported on the requested resource.'}}
[UNKNOWN]: got error 'Base.1.5.QueryNotSupportedOnResource' for API path 'None'
`

**Comment by bb-Ricardo** [comment]
Thank you for the information. will have a look into it next week.

You could try out something in the mena time.
Comment out following line: https://github.com/bb-Ricardo/check_redfish/blob/master/cr_module/classes/vendor.py#L139
And see if it works again.

Cheers
Ricardo

**Comment by robse030** [comment]
Hi Ricardo,

great, everything works again. :)

Greetings
Robert

**Comment by bb-Ricardo** [comment]
Requested information from Fujitsu about this bavahiour.

**Comment by bb-Ricardo** [comment]
Talked to Fujitsu today, It hopefully will be fixed with 2.64

**Comment by bb-Ricardo** [comment]
Still no new version out.

Will close this issue for now and reopen if necessary.
