### ISSUE TITLE
Question regarding "System Log status"

### ISSUE THREAD

**Issue by dan-m-joh** [bb-Ricardo/check_redfish#29]
Hallo Ricardo,

I have a question regarding the `--sel` check.
On one of our servers the `--sel -m 5` check reports the following:
```
[OK]: 2020-09-01T07:29:39Z: Slot 0 Smart Array - Logical drive status changed to ok
[WARNING]: 2020-09-01T07:16:39Z: Slot 0 Smart Array - Logical drive status changed to rebuilding
[WARNING]: 2020-09-01T07:16:09Z: Slot 0 Smart Array - Logical drive status changed to readyForRebuild
[OK]: 2020-09-01T07:16:08Z:   Smart Array - Drive is failed: Port 1I Box 1 Bay 3
```
and the return-code is set to `1` (Warning). 
Is this the expected behavior?
In my case the Rebuild was OK and everything is OK now (note that the Warning was on the 1. Sept).

Regards,
Dan

**Comment by dan-m-joh** [comment]
The only "solution" I can see, is to change `-m 5` to `-m 1`.
Correct?

**Comment by bb-Ricardo** [comment]
Hi Dan,

It shouldn't be that way. Usually there is an relation between both entries.

So that a newer event clears an older event if the new event has a lower severity.

In your case, could you post a `-v` so we can see if there is a relation.

**Comment by dan-m-joh** [comment]
I will send you a PM with the file output.txt from the following cmd:
```
$ check_redfish.py -H xxxxxxxxx -u yyyyyyyy -p zzzzz --sel -m 2 --detail -v 2>output.txt
[OK]: 2020-09-01T07:29:39Z: Slot 0 Smart Array - Logical drive status changed to ok
[WARNING]: 2020-09-01T07:16:39Z: Slot 0 Smart Array - Logical drive status changed to rebuilding
```

Note: This is a  HPE ProLiant DL380 Gen10 server (==> **not** the same as in our other issue).

**Comment by bb-Ricardo** [comment]
Well. Then it's much easier.

Log into ILO, select Integrated Management Log, mark the issues as repaired, Done.

This is a HPE feature which other vendors don't have.

**Comment by dan-m-joh** [comment]
OK, thanks for clarifying.
