### ISSUE TITLE
"Problems" with check_redfish on HPE iLO

### ISSUE THREAD

**Issue by dan-m-joh** [bb-Ricardo/check_redfish#31]
Hello Ricardo,

This is not an issue with check_redfish, but more a general question regarding the redfish implementation in HPE iLO.

Are you aware of any issues/problems with using redfish with HPE iLO.
All of a sudden we get a lot of "`Unable to connect to Host 'xxxxxxxxxx', max retries exhausted.`" errors from check_redfish when accessing our HPE iLO's. (ping to the iLO works as it should).

Any suggestion?

Regards,
Dan

**Comment by bb-Ricardo** [comment]
Hi,

And multiple iLOs started doing this at the same time?

Did you try with the `-v` to see where it might coming from?

**Comment by dan-m-joh** [comment]
No, I did not.
Will try again next time it happens.
It always resolves itself without interaction, sometimes within an hour and sometimes (like this time) it takes more than one day.
As I said, I do not expect check_redfish to be the culprit, I just wanted to know if you kno of any "known issue" with the HPE iLO (we have seen some issues with "ipmi" as well on these servers).

-- 
Dan

**Comment by bb-Ricardo** [comment]
Do you mind if I close this issue?

**Comment by dan-m-joh** [comment]
No, you can go ahead and close it.
