### ISSUE TITLE
keep "overall" output when using --detail

### ISSUE THREAD

**Issue by log1-c** [bb-Ricardo/check_redfish#34]
Hi,

first of all a big thanks for sharing this plugin. It works really well and easy! ❤️ 

I would like to ask if it is possible to keep the "overall" (non-detailed) output of a check when using  `--detail` and put the detailed output in the "extended output".

I'll try to make this more clear with an example :) 

Firmware-Check:
no `--detail` used:
```
# '/usr/lib64/nagios/plugins/check_redfish/check_redfish.py' '--firmware' '-H' 'host' '-p' 'pass' '-u' 'user'
[OK]: Found 19 firmware entries. Use '--detailed' option to display them.
```
Output in Icinga Web 2:
![image](https://user-images.githubusercontent.com/24474580/98786564-8ed63380-23fe-11eb-9a4a-d3103a26feb2.png)

```
$'/usr/lib64/nagios/plugins/check_redfish/check_redfish.py' '--firmware' '-H' 'host' '-p' 'pass' '-u' 'user'
[OK]: Mellanox ConnectX-5 Ex 100 GbE QSFP Adapter - 0C:... (Current-106761-16.26.60.00) (106761): 16.26.60.00
[OK]: BOSS-S1 (Current-106883-2.5.13.3022) (106883): 2.5.13.3022
[OK]: BIOS (Current-159-2.6.4) (159): 2.6.4
[OK]: Broadcom Gigabit Ethernet BCM5720 - F0:... (Current-27481-21.60.2) (27481): 21.60.2
[OK]: Power Supply.Slot.1 (Installed-101095-00.24.83) (101095): 00.24.83
[OK]: OS COLLECTOR, v5.0, A00 (Installed-101734-5) (101734): 5
[OK]: Dell EMC iDRAC Service Module Embedded Package v3.5.1, A00 (Installed-104684-3.5.1) (104684): 3.5.1
[OK]: Mellanox ConnectX-5 Ex 100 GbE QSFP Adapter - 0C:... (Installed-106761-16.26.60.00) (106761): 16.26.60.00
[OK]: Disk 0 on AHCI Controller in slot 1 (Installed-106864-E012) (106864): E012
[OK]: BOSS-S1 (Installed-106883-2.5.13.3022) (106883): 2.5.13.3022
[OK]: BIOS (Installed-159-2.6.4) (159): 2.6.4
[OK]: Dell OS Driver Pack, 19.12.05, A00 (Installed-18981-19.12.05) (18981): 19.12.05
[OK]: Integrated Dell Remote Access Controller (Installed-25227-4.10.10.10) (25227): 4.10.10.10
[OK]: Dell 64 Bit uEFI Diagnostics, version 4301, 4301A42, 4301.43 (Installed-25806-4301A42) (25806): 4301A42
[OK]: Broadcom Gigabit Ethernet BCM5720 - F0:... (Installed-27481-21.60.2) (27481): 21.60.2
[OK]: System CPLD (Installed-27763-1.1.3) (27763): 1.1.3
[OK]: Lifecycle Controller (Installed-28897-4.10.10.10) (28897): 4.10.10.10
[OK]: BIOS (Previous-159-2.5.4) (159): 2.5.4
[OK]: Integrated Dell Remote Access Controller (Previous-25227-4.10.10.10) (25227): 4.10.10.10
```
Output in Icinga Web 2:
![image](https://user-images.githubusercontent.com/24474580/98786623-a57c8a80-23fe-11eb-872f-f22d11968ae9.png)

The output I would like is:
```
$'/usr/lib64/nagios/plugins/check_redfish/check_redfish.py' '--firmware' '-H' 'host' '-p' 'pass' '-u' 'user'
[OK]: Found 19 firmware entries. Use '--detailed' option to display them. [| PERFDATA if check has some]
[OK]: Mellanox ConnectX-5 Ex 100 GbE QSFP Adapter - 0C:... (Current-106761-16.26.60.00) (106761): 16.26.60.00
[OK]: BOSS-S1 (Current-106883-2.5.13.3022) (106883): 2.5.13.3022
[OK]: BIOS (Current-159-2.6.4) (159): 2.6.4
[OK]: Broadcom Gigabit Ethernet BCM5720 - F0:... (Current-27481-21.60.2) (27481): 21.60.2
[OK]: Power Supply.Slot.1 (Installed-101095-00.24.83) (101095): 00.24.83
[OK]: OS COLLECTOR, v5.0, A00 (Installed-101734-5) (101734): 5
[OK]: Dell EMC iDRAC Service Module Embedded Package v3.5.1, A00 (Installed-104684-3.5.1) (104684): 3.5.1
[OK]: Mellanox ConnectX-5 Ex 100 GbE QSFP Adapter - 0C:... (Installed-106761-16.26.60.00) (106761): 16.26.60.00
[OK]: Disk 0 on AHCI Controller in slot 1 (Installed-106864-E012) (106864): E012
[OK]: BOSS-S1 (Installed-106883-2.5.13.3022) (106883): 2.5.13.3022
[OK]: BIOS (Installed-159-2.6.4) (159): 2.6.4
[OK]: Dell OS Driver Pack, 19.12.05, A00 (Installed-18981-19.12.05) (18981): 19.12.05
[OK]: Integrated Dell Remote Access Controller (Installed-25227-4.10.10.10) (25227): 4.10.10.10
[OK]: Dell 64 Bit uEFI Diagnostics, version 4301, 4301A42, 4301.43 (Installed-25806-4301A42) (25806): 4301A42
[OK]: Broadcom Gigabit Ethernet BCM5720 - F0:... (Installed-27481-21.60.2) (27481): 21.60.2
[OK]: System CPLD (Installed-27763-1.1.3) (27763): 1.1.3
[OK]: Lifecycle Controller (Installed-28897-4.10.10.10) (28897): 4.10.10.10
[OK]: BIOS (Previous-159-2.5.4) (159): 2.5.4
[OK]: Integrated Dell Remote Access Controller (Previous-25227-4.10.10.10) (25227): 4.10.10.10
```

This would be consistent to the monitoring plugin guide lines :)
```
SERVICE STATUS: First line of output | First part of performance data
Any number of subsequent lines of output, but note that buffers
may have a limited size | Second part of performance data, which
may have continuation lines, too
```

**Comment by bb-Ricardo** [comment]
Hi,

thank you very much.

you you basically would like to have the full output when `--detailed` is set but the summary as first line?

like?:
```
[OK]: Found 19 firmware entries.
[OK]: Mellanox ConnectX-5 Ex 100 GbE QSFP Adapter - 0C:... (Current-106761-16.26.60.00) (106761): 16.26.60.00
[OK]: BOSS-S1 (Current-106883-2.5.13.3022) (106883): 2.5.13.3022
[OK]: BIOS (Current-159-2.6.4) (159): 2.6.4
[OK]: Broadcom Gigabit Ethernet BCM5720 - F0:... (Current-27481-21.60.2) (27481): 21.60.2
[OK]: Power Supply.Slot.1 (Installed-101095-00.24.83) (101095): 00.24.83
[OK]: OS COLLECTOR, v5.0, A00 (Installed-101734-5) (101734): 5
[OK]: Dell EMC iDRAC Service Module Embedded Package v3.5.1, A00 (Installed-104684-3.5.1) (104684): 3.5.1
[OK]: Mellanox ConnectX-5 Ex 100 GbE QSFP Adapter - 0C:... (Installed-106761-16.26.60.00) (106761): 16.26.60.00
[OK]: Disk 0 on AHCI Controller in slot 1 (Installed-106864-E012) (106864): E012
[OK]: BOSS-S1 (Installed-106883-2.5.13.3022) (106883): 2.5.13.3022
[OK]: BIOS (Installed-159-2.6.4) (159): 2.6.4
[OK]: Dell OS Driver Pack, 19.12.05, A00 (Installed-18981-19.12.05) (18981): 19.12.05
[OK]: Integrated Dell Remote Access Controller (Installed-25227-4.10.10.10) (25227): 4.10.10.10
[OK]: Dell 64 Bit uEFI Diagnostics, version 4301, 4301A42, 4301.43 (Installed-25806-4301A42) (25806): 4301A42
[OK]: Broadcom Gigabit Ethernet BCM5720 - F0:... (Installed-27481-21.60.2) (27481): 21.60.2
[OK]: System CPLD (Installed-27763-1.1.3) (27763): 1.1.3
[OK]: Lifecycle Controller (Installed-28897-4.10.10.10) (28897): 4.10.10.10
[OK]: BIOS (Previous-159-2.5.4) (159): 2.5.4
[OK]: Integrated Dell Remote Access Controller (Previous-25227-4.10.10.10) (25227): 4.10.10.10
```

Then in the status short output you would only see `[OK]: Found 19 firmware entries.` and in once you click on the service you see the full output?

If I understood it correctly then it makes totally sens and should be possible without much hassle.

let me know if this is correct.

**Comment by log1-c** [comment]
Yes, that is exactly what I want.
And way easier explained as my mumbling :D Was a bit too early, it seems^^

**Comment by bb-Ricardo** [comment]
great, then I will add  it as soon as I get around working on this again, hopefully by next week.

Then I also need to finish up with version 1.1

**Comment by bb-Ricardo** [comment]
Hi,

finally got around to change it. It is in branch `next-release`. can you try it out and see if this is what you anted?

And thanks for all this hours of community work in the Icinga community forum. That's highly appreciated.

**Comment by log1-c** [comment]
Hi @bb-Ricardo 
looks good for the firmware check :)
Tbh I was aiming at having the summary output for all checks when adding a `--detail`, though :D

**Comment by bb-Ricardo** [comment]
Ohh, for every check? let me think about that.

**Comment by bb-Ricardo** [comment]
I'm still trying to implement this. But having following issue.

If (in detailed view) an error occurs it should be displayed in the first line. Because we forward this status to another alarming system and they more or less see only the first line because it doesn't support line breaks (looking at you IBM).

That would require to move the summary below all "alarm lines".

The other approach would be to display the summary only if all lines are 'OK'.

Any thoughts on this?

**Comment by log1-c** [comment]
Hi :)

My thoughts:
If there is an alarm _I_ am also okay with not having a summary line and having the rest of the detailed output below the alarm.
Perfect example right here:
![image](https://user-images.githubusercontent.com/24474580/104158074-dff9a800-53ec-11eb-9cf3-a919d890e171.png)
This is totally fine with me like this.
(off-topic question: do you might know how to get rid of the alarm for a not installed CPU?)

If there is no alarm, display a summary at first, then the detailed output below. Like the firmware check is already doing.

**Comment by bb-Ricardo** [comment]
Thank you for the detailed answer. In the meantime I came to the same conclusion.

I'm currently fixing a bug which also rewrites the plugin out text assembly.

I might just put it all in one change. Hopefully finish this by this week.

**Comment by bb-Ricardo** [comment]
So, finally got around to finish this one.

Sorry for the long delay. Can you give it a try?

Thank you

**Comment by log1-c** [comment]
I like it <3

Thanks a lot for your work!
