### ISSUE TITLE
Session file is readable for everyone

### ISSUE THREAD

**Issue by kaistian** [bb-Ricardo/check_redfish#46]
The session file is created with the users umask and is often 0002.
That means that the file is open for everyone since the mode will be 0644 and anyone can use the file to gain access to the management without a password.

**Comment by bb-Ricardo** [comment]
Thank you very much. This is absolute correct and should not be that way.

Why didn't I think of this?

Will change this asap.

**Comment by bb-Ricardo** [comment]
Hi @kaistian,

I pushed a change to next-release branch. Can you test it please and report back?

Thank you.

**Comment by matejzero** [comment]
I can confirm sessions files created with next-release branch have correct permissions (600).

**Comment by bb-Ricardo** [comment]
Great. Also existing session files should have the changed permissions. Can you confirm that?

**Comment by matejzero** [comment]
Yes. I updated the plugin today and session files from Jan 19 also had updated permissions.

I did a double chec, changed permissions to 666 for all session files and I can see check fixing them back to 600.

**Comment by bb-Ricardo** [comment]
Thank you very much for this extensive testing. Highly appreciated.

**Comment by kaistian** [comment]
I can also confirm it changes the permission, but this create another issue.
For the first user it works OK, but since everybody users the same file name on the session file it will not work for the second user and you get a permission denied.

The change does changes the permission after the fact, so the file is saved with wide open permission and then restricted, this open a wide range of attacks like using inotify to copy the file to another location before the permission is changed.

**Comment by bb-Ricardo** [comment]
> I can also confirm it changes the permission, but this create another issue.
> 
> For the first user it works OK, but since everybody users the same file name on the session file it will not work for the second user and you get a permission denied.

I don't really understand which scenario you're describing here.


> The change does changes the permission after the fact, so the file is saved with wide open permission and then restricted, this open a wide range of attacks like using inotify to copy the file to another location before the permission is changed.

Do you mean a race condition that the file permissions are insufficient between creating the file for the first time and then changing the permissions shortly after?

**Comment by kaistian** [comment]
> I don't really understand which scenario you're describing here.

The default session filename and directory is the same for all users, lets say a server has 2 users jack and jill.
If jack runs check_redfish first it runs fine and he creates the seesion file /tmp/check_redish_redfishhost.session
When jill run check_redfish against same host she will get a permission denied since only jack has permission to /tmp/check_redish_redfishhost.session.

One way to mitigate this is to add the uid to the session filename.

> Do you mean a race condition that the file permissions are insufficient between creating the file for the first time and then changing the permissions shortly after?

Yes

**Comment by bb-Ricardo** [comment]
> > I don't really understand which scenario you're describing here.
> 
> The default session filename and directory is the same for all users, lets say a server has 2 users jack and jill.
> If jack runs check_redfish first it runs fine and he creates the seesion file /tmp/check_redish_redfishhost.session
> When jill run check_redfish against same host she will get a permission denied since only jack has permission to /tmp/check_redish_redfishhost.session.
> 
> One way to mitigate this is to add the uid to the session filename.

How about adding this information to the README? Otherwise I would need to add a migration scenario to the script to move existing session files to the new naming schema. Also `--sessionfile` and `--sessionfiledir` are meant to mitigate this issue.  
 
> > Do you mean a race condition that the file permissions are insufficient between creating the file for the first time and then changing the permissions shortly after?
> 
> Yes

I will add this the coming days.

**Comment by kaistian** [comment]
> > One way to mitigate this is to add the uid to the session filename.
> 
> How about adding this information to the README? Otherwise I would need to add a migration scenario to the script to move existing session files to the new naming schema. Also `--sessionfile` and `--sessionfiledir` are meant to mitigate this issue.

Personally I prefer programs that play nice in default settings, but would you need to move the existing session files?
Wouldn't it just create new session files and the old ones would expire after a short time unless someone have set a very high timeout on session?

Could also write that in the README, that people need to delete old session files since they are not secured.

**Comment by bb-Ricardo** [comment]
Hey @kaistian,

finally got around to look into this again. I implemented your suggestions including a session file migration.
This way the user doesn't have to clean up a ton of old session files.

Can you test it and see if it works.

Also added a mitigation to the race condition that the file is world readable when opened for the first time. Now we create a file handler with the proper umask set already.
Can you have a look at this as well?

Thank you.
