### ISSUE TITLE
Question: Is it possible to ignore not installed CPUs?

### ISSUE THREAD

**Issue by log1-c** [bb-Ricardo/check_redfish#47]
Hi,
(me again)
I have a question regarding the sys-info check:

Is it possible to ignore a not installed CPU?
Reason is, that the check is going to critical state because the 2nd CPU slot is "Enabled/Unknown":
![image](https://user-images.githubusercontent.com/24474580/105816635-d491a980-5fb4-11eb-95c3-11bacf742042.png)

The server just has a single cpu, and my co-worker and me did not find an option in the iDrac settings to change the behavior (no "error" in IDrac either).

I helped my self and hacked a 
```
elif dell_sensor.get('HealthState') == "Unknown":
                            this_sensor_status = "OK"
```
into line 145 of `check_redfish/cr_module/system_chassi.py`, but I do not like it very much, because we could miss some other real errors like that.

Thanks again for the nice script!

**Comment by bb-Ricardo** [comment]
Can you test the "next-release" branch? It schould be fixed their.

**Comment by log1-c** [comment]
It is, message is not shown anymore!
Thanks!
