### ISSUE TITLE
Setting -w and/or -c with and --mel causes exception on DL360 Gen10

### ISSUE THREAD

**Issue by jhofmueller** [bb-Ricardo/check_redfish#49]
I noticed that some log entries will not have a timestamp and hence cause an exception in the event.py module:

```
Traceback (most recent call last):
  File "./check_redfish.py", line 210, in <module>
    if any(x in args.requested_query for x in ['mel', 'all']):      get_event_log(plugin, "Manager")
  File "/home/jogi/git/nwmon/check_redfish/cr_module/event.py", line 134, in get_event_log
    get_event_log_hpe(plugin_object, event_type, event_entries_redfish_path)
  File "/home/jogi/git/nwmon/check_redfish/cr_module/event.py", line 210, in get_event_log_hpe
    if entry_date > date_critical.astimezone(entry_date.tzinfo) and severity != "OK":
AttributeError: 'NoneType' object has no attribute 'tzinfo'
```
From what I can tell this happens after the machine was power cycled.  My suggestion is to return *OK* for log entries without timestamp.  Otherwise they would stay on Warning/Critical forever (or until you manage to clear the log).

**Comment by bb-Ricardo** [comment]
Hi,

This should not happen and I thought I have taken care of it. Obviously not good enough.

As you can't acknowledge MEL alarms they are "aging out" with critical and warning. This should be described in the [README.md](README.md).

I will have a look why it fails.

**Comment by jhofmueller** [comment]
Turns out that log entries without timestamp are reported with date/time '0000-00-00T00:00:00Z'  which is an illegal date.  This case is currently not handled by the code.

**Comment by jhofmueller** [comment]
Maybe you like my solution :wink:

**Comment by bb-Ricardo** [comment]
> Turns out that log entries without timestamp are reported with date/time '0000-00-00T00:00:00Z' which is an illegal date. This case is currently not handled by the code.

Well technically this is not an illegal date, the signed 32bit UNIX timestamp isn't aware of this 2000 years old log entries 😄 

I'll have a look at your PR soon. Thank you for this contribution.

**Comment by bb-Ricardo** [comment]
added a fix to "next-release" branch. Sorry I didn't use your PR.

Can you test and see if the current fix solves your problem as well?

Thanl you

**Comment by jhofmueller** [comment]
The current fix looks good!  I like your version better than mine anyhow :smile:
