### ISSUE TITLE
Add testing framework with Mockup data

### ISSUE THREAD

**Issue by bb-Ricardo** [bb-Ricardo/check_redfish#5]
This should make use of these projects:
https://github.com/DMTF/Redfish-Mockup-Creator
https://github.com/DMTF/Redfish-Mockup-Server

**Comment by bb-Ricardo** [comment]
Not sure how to implement this for all the differnt vendors without exposing to much sensitive data.

sure you can remove serials, firmware versions, part numbers, mac and ip addresses. But still it would provide loads of data which would reveal infrastructure information.

Any Ideas on that anyone?

**Comment by matejzero** [comment]
If you remove stuff you mention, what infra information would it reveal? Can you give me an example to have a better understanding?

**Comment by bb-Ricardo** [comment]
> If you remove stuff you mention, what infra information would it reveal? Can you give me an example to have a better understanding?

Don’t know if type of cpu, amount and size of hard drives are giving away to much information?

Probably not.

And the other issue is: would different vendors mind if their bmc data/redfish model/implementation be publicly available on GitHub?
Do you agree any sort of NDA by buying the hardware and get granted the usage of the BMC software?
Competitors could check up on each others state of BMC implementation.

Or am I just to paranoid?

**Comment by matejzero** [comment]
I don't think they are. You only collect mockup from 1 server of certain model, not all your infra.

I don't sign any NDA and you can buy supermicro/lenovo/dell servers / boards in various online shops without any NDA.

Most of Redfish API implementations have public reference docs:
- [Lenovo](https://sysmgt.lenovofiles.com/help/topic/com.lenovo.systems.management.xcc.doc/REST_API_user_manual.pdf)
- [Dell](https://www.dell.com/support/manuals/my/en/mybsd1/idrac7-8-lifecycle-controller-v2.40.40.40/redfish%202.40.40.40/chassis&lang=en-us)

So I don't think this is a problem, but it's good to be careful.

**Comment by bb-Ricardo** [comment]
Thank you for the prompt reply and thoughts on that topic.

I guess I will start a separate repo with the mockups and a little script to scrub sensitive data.

**Comment by bb-Ricardo** [comment]
Just not worth the hassle. keep using my internal one.
