### ISSUE TITLE
Ignoring older log entries with --sel fails on DL360 Gen10

### ISSUE THREAD

**Issue by jhofmueller** [bb-Ricardo/check_redfish#50]
Log entries from system event log (--sel) are of type "System" and hence excepted from the **age check** in the event.py module.  This makes it impossible to set thresholds for these log entries.

**Comment by bb-Ricardo** [comment]
Hi, I don't really understand this issue.

What are you trying to do and what should be the expected outcome?

**Comment by jhofmueller** [comment]
I am trying to run a check like this
```
check_redfish.py -H IP_ADDR --sel -f AUTHFILE -w 3 -c 1
```
According to the README I should get OK and return value 0 since all log entries regarding errors/warnings are older than three days.  Instead I get CRITICAL for an older log entry.  I checked the code and found out that the age of a log entry is only checked if the event_type != "System".  Check line 201 ff in cr_module/event.py

**Comment by bb-Ricardo** [comment]
Ah, HPE has this great feature of marking events in SEL as "repaired". Just log in to your ILO and set the entries as repaired, alarm will be gone.

This is a great feature but only HPE provides this for IML.

**Comment by bb-Ricardo** [comment]
Did my suggestion solve your issue?

**Comment by jhofmueller** [comment]
Yes, that works!
