### ISSUE TITLE
Add basic Gigabyte and Inspur support

### ISSUE THREAD

**Issue by hpcitdude** [bb-Ricardo/check_redfish#53]
Hi,

When doing checks on Gigabyte enclosure/blade system H262 Z61 I found that individual PSU's Status is not working.
This is because when checking enclosure bmc device we can see the PSU's but there is no Status entry for each PSU, so there is nothing to check. :-/
An example below:
{
        "@odata.id":"/redfish/v1/Chassis/Self/Power#/PowerSupplies/1",
        "Manufacturer":"DELTA",
        "MemberId":"1",
        "Model":"DPS-3200AB-1 B",
        "Name":"DPS-3200AB-1 B",
        "PartNumber":"XXXXXXXXXXXXXXXX",
        "SerialNumber":"yyyyyyyy"
}

The blades itself do not have PSUs and for the ´the easy fix is to not run --power :)

but on the enclosures we need to get --power to work, I will send you a mockup separately. 

Thanks,
Pierre

**Comment by bb-Ricardo** [comment]
thank you very much for the MockUp.

I hope I will have some time next week to add this as well.

**Comment by bb-Ricardo** [comment]
I had a look and this Gigabyte implementation barely reports anything.

**Comment by bb-Ricardo** [comment]
Hi, can you test the "next-release" branch?

**Comment by hpcitdude** [comment]
Hi, sure. But first. I got this from Gigabyte support. They confirm Ami Redfish do not support health status right now and we can only check for existing PSU's and AC lost. This is how it look like if PSU is there:
![gigabyte_psu_1](https://user-images.githubusercontent.com/39642964/116233714-f0dfe680-a75b-11eb-8460-13e8cdd7d47f.png)

This is how it looks like if it is not, (N/A) on some fields.
![gigabyte_psu_2](https://user-images.githubusercontent.com/39642964/116233875-25ec3900-a75c-11eb-8664-f5797418bc86.png)

**Comment by bb-Ricardo** [comment]
So in Ami we have to assume that a missing power supply is a Critical issue? What if the power supply was pulled out on purpose and the server should only be running with one PS?

I've added the power control health status. Maybe this turns Critical if a power supply is faulty.

Would you be able to check that?

**Comment by hpcitdude** [comment]
Right now, we have only PSUs with good health :)
So I can only replug a PSU as test for now.

I am also thinking of the one PSU situation. hm. In our case we always want 2 working. So for us it is critical with a failed one or running with only one PSU.

But there might be other users out there wanting just one PSU ? Not sure. This is a 4 blade chassi also, so it is a bit risky to run 4 servers using only one PSU. Perhaps stear it with an input flag? --num-psu ?

I've talked to my team also, in case we get a failed done, we will test this and extract info from Redfish.

/Pierre

**Comment by bb-Ricardo** [comment]
Hi,

I didn't want to more and too specific cli options.

Is it ok if I close this for now?

**Comment by hpcitdude** [comment]
Hi, yest it is ok. thanks!
