### ISSUE TITLE
Add proper support for multiple chassis

### ISSUE THREAD

**Issue by hpcitdude** [bb-Ricardo/check_redfish#54]
Hi,

When I tried the check_redfish plugin on a Huawei bladecenter G560 it seems like there is a bug for object id's on Temperate and Fan sensors.

I get output like this on stdout:

Object id '0' for 'Temperature' already used
Object id '1' for 'Temperature' already used
Object id '2' for 'Temperature' already used
Object id '3' for 'Temperature' already used
Object id '4' for 'Temperature' already used
Object id '5' for 'Temperature' already used
Object id '6' for 'Temperature' already used
Object id '7' for 'Temperature' already used
Object id '8' for 'Temperature' already used
Object id '9' for 'Temperature' already used
Object id '10' for 'Temperature' already used
Object id '11' for 'Temperature' already used
Object id '12' for 'Temperature' already used
Object id '13' for 'Temperature' already used
Object id '14' for 'Temperature' already used
Object id '15' for 'Temperature' already used
Object id '16' for 'Temperature' already used
Object id '17' for 'Temperature' already used
Object id '18' for 'Temperature' already used
Object id '19' for 'Temperature' already used
Object id '20' for 'Temperature' already used
Object id '21' for 'Temperature' already used
Object id '22' for 'Temperature' already used
Object id '23' for 'Temperature' already used
Object id '24' for 'Temperature' already used
Object id '25' for 'Temperature' already used
Object id '26' for 'Temperature' already used
Object id '27' for 'Temperature' already used
Object id '28' for 'Temperature' already used
Object id '29' for 'Temperature' already used
Object id '30' for 'Temperature' already used
Object id '31' for 'Temperature' already used
Object id '32' for 'Temperature' already used
Object id '0' for 'Fan' already used
Object id '1' for 'Fan' already used
Object id '2' for 'Fan' already used
Object id '3' for 'Fan' already used
Object id '4' for 'Fan' already used
Object id '5' for 'Fan' already used
Object id '6' for 'Fan' already used
Object id '7' for 'Fan' already used
Object id '8' for 'Fan' already used
Object id '9' for 'Fan' already used
Object id '10' for 'Fan' already used
Object id '11' for 'Fan' already used

The rest of the checks work ok though. The perfdata is not complete, which I suspect is due to the bug above.

I'll send a mockup of this also.

Regards,
Pierre

**Comment by bb-Ricardo** [comment]
super, thank you.

**Comment by bb-Ricardo** [comment]
Were you able to create a Mockup?

**Comment by hpcitdude** [comment]
Hi, sorry for late answer, busy week. Sent you the mockup to your email just now :)

**Comment by bb-Ricardo** [comment]
Hi,

I just fixed the support for multiple chassis. Can you give it a try and let me know?

Thank you.

**Comment by hpcitdude** [comment]
Hi Ricardo,

i tried the code in next-release branch and it works with the g560 box. Thanks for adding this :)

/Pierre
