### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'lower'

### ISSUE THREAD

**Issue by Bes0n** [bb-Ricardo/check_redfish#57]
iLO Firmware has been updated to 2.31 Oct 13 2020. Was working without any issues before update. 

/local/lib/nagios/plugins/redfish/check_redfish.py -H <host_address> --memory
Traceback (most recent call last):
  File "/local/lib/nagios/plugins/redfish/check_redfish.py", line 194, in <module>
    plugin.rf.determine_vendor()
  File "/local/lib/nagios/plugins/redfish/cr_module/classes/redfish.py", line 427, in determine_vendor
    if self.vendor_data.ilo_version.lower() == "ilo 5":
AttributeError: 'NoneType' object has no attribute 'lower'

**Comment by Bes0n** [comment]
I removed attribute lower for now and looks like it's working, but not sure it's properly executing in background now.

**Comment by bb-Ricardo** [comment]
Hi,

Which version are you using. There was a fix for this issue in the last release.

**Comment by Bes0n** [comment]
Hi Ricardo, 

Thank you for your reply. 

Version is following: `Version: 1.0.0 (2020-04-23)`

**Comment by bb-Ricardo** [comment]
Yes, then just istall 1.2.0 and this issue should be resolved.

**Comment by Bes0n** [comment]
Thank you. Will try that. I will close the case then.
