### ISSUE TITLE
Fujitsu Server - Unable to retrieve disk info

### ISSUE THREAD

**Issue by robse030** [bb-Ricardo/check_redfish#58]
Hi, after upgrading the irmc-firmware to the latest version, I get the following error message when I query the firmware:  Request error: Unable to retrieve disk info: /redfish/v1/Systems/0/Storage/1/Drives/9

The current version of the plugin is also installed.

Kind regards
Robert

**Comment by bb-Ricardo** [comment]
Hi,

I guess you installed iRMC version 3.06P?

This is an interesting issue.

Can you run the check with the `-v` and the `-d` options enabled and add the output here (make sure to obfuscate serial numbers).

Also what does the iRMC report?

Currently I try to adapt to Firmware 3.0 as in my setup the storage is rported twice.

**Comment by robse030** [comment]
Hi Ricardo,

that's right. It's 3.06P.

Attached the log-file:
[output.txt](https://github.com/bb-Ricardo/check_redfish/files/6351770/output.txt)

**Comment by bb-Ricardo** [comment]
can you try out the "next-release" branch? I added some changes.

But the data for this device is pretty much not existent.

**Comment by robse030** [comment]
Hi,
unfortunately the problem persists.

**Comment by bb-Ricardo** [comment]
mhh. I just tested it with your data as example and the plugin reported the drive like this:
```
[OK]: Physical Drive None [ 0 : 1 : PCI Slot : 9 ] (PCIeSSD Slot9 / SSD / NVMe) 0GiB status: OK
```

Make sure you did a `git pull` and a `git checkout next-release`.

**Comment by robse030** [comment]
Hi Ricardo,

sorry you're right. Everything is right now.
Thank you.

**Comment by bb-Ricardo** [comment]
great to hear.
