### ISSUE TITLE
Expected behaviour for iDRAC Firmware check

### ISSUE THREAD

**Issue by lp4775** [bb-Ricardo/check_redfish#63]
--firmware uses power.py to retrieve this information. If there are no power supplies avalible via the API then the firmware check is displayed as UNKNOWN despite there being plenty or readings wrt other firmware versions.

Is this expected? I would have presumed that if no power supplies were avalible, then the firmware check would simply omit this result.

**Comment by bb-Ricardo** [comment]
You are correct, this is what I would assume as well.

Do you want to try to fix it?

**Comment by lp4775** [comment]
Yes, I'll PR the fix later when I get a sec
