### ISSUE TITLE
Unknown status when checking --storage on Gigabyte blades

### ISSUE THREAD

**Issue by hpcitdude** [bb-Ricardo/check_redfish#64]
Hi,

I have an issue with GIGABYTE H262-Z61 nodes. --storage check gives unknown status. No ctrl or disk detected.
Running with options:
 --nosession --storage

Give output:
[UNKNOWN]: No storage controller and disk drive data found in system

**Comment by hpcitdude** [comment]
I generated the mockup and checked. On our nodes there are no ctrl installed. Just a simple disk, so the disk is not available under:
/redfish/v1/Systems/Self/Storage

But we can find it under:
/redfish/v1/Systems/Self/SimpleStorage

instead.

**Comment by bb-Ricardo** [comment]
Hi,

The script checks both path `Storage` and `SimpleStorage`. All I get from the `SimpleStorage` path is this:
```
{
    "@odata.context": "/redfish/v1/$metadata#SimpleStorage.SimpleStorage",
    "@odata.etag": "W/\"1620375527\"",
    "@odata.id": "/redfish/v1/Systems/Self/SimpleStorage/1",
    "@odata.type": "#SimpleStorage.v1_2_2.SimpleStorage",
    "Description": "This resource shall be used to represent a storage controller and its directly-attached devices.",
    "Devices": [
        {
            "CapacityBytes": 503424483328,
            "Model": "INTEL SSDSC2KB480G8",
            "Name": "INTEL SSDSC2KB480G8"
        }
    ],
    "Id": "1",
    "Links": {
        "Chassis": {
            "@odata.id": "/redfish/v1/Chassis/Self"
        }
    },
    "Name": "Simple Storage"
}
```

But since there is no `id` or `status` the script ignores it. I don't think this is helpful in any way.

Cheers
Ricardo

**Comment by hpcitdude** [comment]
Hi,

Ok. That is to bad. Hm, so we can only check if there is a device attached or not ...

If there would have been a "status" to check for each member in SimpleStorage, would the script work then? Even though there is no controller card installed?

I will also check with Gigabyte about this.

Regards,
Pierre

**Comment by bb-Ricardo** [comment]
If the output would look like this:
```
{
    "@odata.context": "/redfish/v1/$metadata#SimpleStorage.SimpleStorage",
    "@odata.etag": "W/\"1620375527\"",
    "@odata.id": "/redfish/v1/Systems/Self/SimpleStorage/1",
    "@odata.type": "#SimpleStorage.v1_2_2.SimpleStorage",
    "Description": "This resource shall be used to represent a storage controller and its directly-attached devices.",
    "Devices": [
        {
            "CapacityBytes": 503424483328,
            "Model": "INTEL SSDSC2KB480G8",
            "Name": "INTEL SSDSC2KB480G8",
            "Status": {
                "State": "Enabled",
                "Health": "OK"
            }
        }
    ],
    "Id": "1",
    "Links": {
        "Chassis": {
            "@odata.id": "/redfish/v1/Chassis/Self"
        }
    },
    "Status": {
        "State": "Enabled",
        "Health": "OK"
    },
    "Name": "Simple Storage"
}
```

The plugin would pick up the storage controller and the output would change to this:
```diff
-[UNKNOWN]: No storage controller and disk drive data found in system
+[OK]: All storage controllers (1) are in good condition (No system drives found)
+[OK]: Simple Storage status: OK
+[OK]: None INTEL SSDSC2KB480G8 INTEL SSDSC2KB480G8 (size: 503.42 GiB) status: OK
```

This means:
* The simple storage needs a status and `State` must be `Enbaled`
* Each drive needs a status and `State` must be `Enabled`

Maybe you can have a chat with the Gigabyte engineers. It would not be the prettiest output but at least something.

Cheers
Ricardo

**Comment by bb-Ricardo** [comment]
can I close this issue?
