### ISSUE TITLE
check_redfish.py reports "no memory information"

### ISSUE THREAD

**Issue by dan-m-joh** [bb-Ricardo/check_redfish#66]
Hello Ricardo,

First of all thanks for a great check script.

When I run a "memory" check on one of our Huawei XH620 V3 Blades it comes bacl as "Unknown":
```
$ ./check_redfish.py -H xxxxxx -u <user> -p <password> --memory --detailed
[UNKNOWN]: Request error: Returned data from API URL '/redfish/v1/Systems/Blade4/Memory' contains no memory information
```
The "info" check also says "MEM: 0GB":
```
$ ./check_redfish.py -H xxxxxx -u <user> -p <password> --info
[OK]: INFO: Huawei XH620 V3 (CPU: 2, MEM: 0GB) - BIOS: 5.15 - Serial: xxxxxxxxxxxxxxxxxxxxx - Power: On - Name: NOT SET
```
Other blades of the same type does not have the same problem - just this one.
Here is an example of another blade in the same chassis:
```
$ ./check_redfish.py -H zzzzzzz -u <user> -p <password> --memory --detailed
[OK]: All 4 memory modules (Total 128.0GB) are in good condition
[OK]: Memory module DIMM000 (32.0GB) status is: OK
[OK]: Memory module DIMM010 (32.0GB) status is: OK
[OK]: Memory module DIMM100 (32.0GB) status is: OK
[OK]: Memory module DIMM110 (32.0GB) status is: OK
```
Any suggestions?
I can provide a --verbose via PM if you need/want.

Regards,
Dan

**Comment by dan-m-joh** [comment]
Hello Ricardo,

Before you invest to much time in this!
I have just found out that we probable have an issue with this blade (looking at iBMC some fields (that should be filled) are empty, like Memory and some CPU info).
We will try to get an timeslot to reseat this blade sometime next week.

Sorry for the trouble!

Dan

**Comment by bb-Ricardo** [comment]
No Problem, then I will close this for now.
