### ISSUE TITLE
Problem with plugin ouput, it returns with ERROR, but doesn't show issue

### ISSUE THREAD

**Issue by gabortakacs78** [bb-Ricardo/check_redfish#68]
Hi,

we faced an issue when "--info" return with CRITICAL, but output doesn't show issue:
/check_redfish.py -H 'x.x.x.x' -u 'xxx' -p 'xxx' '--info' '--max' '10' '--retries' '10'
[CRITICAL]: INFO: Dell Inc. PowerEdge R740xd (CPU: 2, MEM: 1536GB) - BIOS: 2.3.10 - Serial: CNIVC0xxxxxxxx - ServiceTag: 5xxxxx2 - Power: On - Name: xxxxxxxx - 63 health sensors are in 'OK' state

If I check verbose output, it just shown CRITICAL for:
Body Response of /redfish/v1/Systems/System.Embedded.1:
...
 'Status': {'Health': 'Critical',
            'HealthRollup': 'Critical',
            'State': 'Enabled'},

We can we determine in this case what could be the problem?
Is there any possibility to modify output in this case and show the problematic segment?

Plugin version: 1.3.0 (same issue with 1.3.1)

.

**Comment by bb-Ricardo** [comment]
Hi,

Can you try running it with `--all --detail`. Are there any faulty components?

**Comment by gabortakacs78** [comment]
Hi,

yes, here you are:
> check_redfish.py -H '10.241.129.141' -u 'xxx' -p 'xxx' '--info' --all --detail
[CRITICAL]: 2021-10-01T03:00:57+02:00: Correctable memory error logging disabled for a memory device at location DIMM_B2.
[CRITICAL]: 2021-09-30T14:56:43+02:00: Correctable memory error logging disabled for a memory device at location DIMM_B12.
[CRITICAL]: 2021-09-10T21:35:20+02:00: Correctable memory error logging disabled for a memory device at location DIMM_B12.
[CRITICAL]: 2021-09-05T17:45:02+02:00: Correctable memory error logging disabled for a memory device at location DIMM_B7.
[CRITICAL]: INFO: Dell Inc. PowerEdge R740xd (CPU: 2, MEM: 1536GB) - BIOS: 2.3.10 - Serial: CNIVC009480946 - Power: On - Name: AUDEINGHVPSPR02.SPRITE01.vwgroup.com
[WARNING]: 2021-09-30T14:56:42+02:00: Correctable Machine Check Exception detected on CPU 2.
[WARNING]: 2021-09-05T17:45:00+02:00: Correctable Machine Check Exception detected on CPU 2.
[OK]: BMC: iDRAC 9 (Firmware: 3.36.36.36) and all nics are in 'OK' state.
[OK]: All fans (6) are in good condition and fan redundancy status is: Enabled
[OK]: Found 30 firmware entries.
...

Br,
Taki

**Comment by gabortakacs78** [comment]
Hmmm, based on this output and our monitoring logs,
it returned with CRITICAL since around 2021-10-01 03:00...
And before that it became to CRITICAL around 2021-09-05 17:47...
So maybe it is caused by WARNINGS:
[WARNING]: 2021-09-30T14:56:42+02:00: Correctable Machine Check Exception detected on CPU 2.
[WARNING]: 2021-09-05T17:45:00+02:00: Correctable Machine Check Exception detected on CPU 2.

So now we knows why it is CRITICAL.
But why output doesn't show it? ;-)

**Comment by bb-Ricardo** [comment]
This is a good question. This plugin only returns the status reported by iDRAC. If this is a bit "wonky" then the plugin can't do anything about it.

The system health is more like a summery from different components. So it depends on the state of other components what is actually returned.

I also removed your uploaded output and edited your comment with the output. It all contained sensitive data.

**Comment by gabortakacs78** [comment]
Hi,

OK, thanks for your help.
Then is similar cases we will check detailed output.
Also thanks for removing sensitive data. I tried to delete it from attachement, but it looks i was not enough careful...)
