### ISSUE TITLE
Not able to get firmware infos after iDRAC-Update

### ISSUE THREAD

**Issue by robse030** [bb-Ricardo/check_redfish#69]
Hi, after upgrading the firmware on my PowerEdge R7525 Server to version 4.32.10.00, i'am not able to read the firmware infos.

The logs are attached
[Output_check.txt](https://github.com/bb-Ricardo/check_redfish/files/7467564/Output_check.txt)
.
[FirmwareInventory.json.txt](https://github.com/bb-Ricardo/check_redfish/files/7467568/FirmwareInventory.json.txt)

Regards,
robert

**Comment by bb-Ricardo** [comment]
This looks like a bug in the iDRAC firmware.

can you try to comment out following line and see if it works:
https://github.com/bb-Ricardo/check_redfish/blob/e486e43a9f44a27b97eff92a6efb77f3c0adc72d/cr_module/classes/vendor.py#L108

Cheers
Ricardo

**Comment by robse030** [comment]
Sorry, wrong output in the firt post. Here is the right one. :)

[FirmwareInventory.json.txt](https://github.com/bb-Ricardo/check_redfish/files/7467639/FirmwareInventory.json.txt)
