### ISSUE TITLE
Remove netbox plugin topic

### ISSUE THREAD

**Issue by DanSheps** [bb-Ricardo/check_redfish#71]
Hello,

Could you kindly remove the netbox-plugin topic from your topic list on the repository.  It is misleading as this is not a netbox-plugin that integrates into our plugin framework.

Thanks

**Comment by bb-Ricardo** [comment]
Hi Daniel,

no problem, wasn't aware that theses topics were so essential. I removed it.

**Comment by DanSheps** [comment]
Thanks!  We use that topic to redirect people who are looking for a plugin so it is best if we can keep it to only things that integrate into netbox's plugin system.

Thanks for your attention to the matter!

**Comment by bb-Ricardo** [comment]
Sure, no problem. And thanks for this awesome piece of Software. Keep up the good work.
