### ISSUE TITLE
HP Synergy refuses all requests

### ISSUE THREAD

**Issue by flohoff** [bb-Ricardo/check_redfish#81]
Hi,
i am trying to use check_redfish on a HP Synergy Management Node running OneView. For all requests i see this:

`Body Response of /redfish/v1/: b'{"errorSource":null,"data":{},"details":"The requested resource could not be found.","message":"Not Found","messageParameters":[],"nestedErrors":[],"errorCode":"GENERIC_HTTP_404","recommendedActions":["Check the request URI, then resend the request.","Verify if the request requires an X-API-Version header."]}'
`
Request is as follows:

```
2022-03-17 11:04:35,544 - DEBUG: HTTP REQUEST: GET
	PATH: /redfish/v1/
	BODY: None
2022-03-17 11:04:35,544 - INFO: Attempt 1 of /redfish/v1/
2022-03-17 11:04:35,688 - INFO: Response Time for GET to /redfish/v1/: 0.043490524403750896 seconds.
2022-03-17 11:04:35,688 - DEBUG: HTTP RESPONSE for /redfish/v1/:
Code: 404 Not Found
Headers:
	Date: Thu, 17 Mar 2022 10:00:13 GMT
	Server: Apache
	Cache-Control: no-cache
	Pragma: no-cache
	Vary: Accept-Language,Accept
	Content-Language: en
	Expires: 0
	X-Frame-Options: DENY
	Strict-Transport-Security: max-age=31536000
	X-XSS-Protection: 1; mode=block
	X-Content-Type-Options: nosniff
	cache-control: no-cache
	Keep-Alive: timeout=15, max=100
	Connection: Keep-Alive
	Transfer-Encoding: chunked
	Content-Type: application/json; charset=UTF-8

Body Response of /redfish/v1/: b'{"errorSource":null,"data":{},"details":"The requested resource could not be found.","message":"Not Found","messageParameters":[],"nestedErrors":[],"errorCode":"GENERIC_HTTP_404","recommendedActions":["Check the request URI, then resend the request.","Verify if the request requires an X-API-Version header."]}'
```

**Comment by bb-Ricardo** [comment]
Hi,

HP OneView is not supported. HP supposedly implements a "version" of Redfish but it's not working like the specified official Redfish Standard.

And as you can see "/redfish/v1" -> 404

You could use OneView to provision Monitoring credentials.

But in the end you need to query all Server via iLO.

**Comment by bb-Ricardo** [comment]
Does this "answer" your request? Even though it is not a real fix?

Can I close this issue?

**Comment by flohoff** [comment]
Yes - I am sorry for the noise. Seems HP did some pretty "cool things" :(

**Comment by bb-Ricardo** [comment]
Don't worry. Is there no plugin out there which queries HPOV for health status of systems management by this OV instance?

Never really investigated.

Also usually don't like the idea of relying on a the life of a single instance to monitor the status of a fleet of systems.
