### ISSUE TITLE
Connection Issues to iDRAC9

### ISSUE THREAD

**Issue by madmax01** [bb-Ricardo/check_redfish#82]
Hi,

is there an known issue on Centos8?

PowerEdge R650 
iDRAC FW 5.10.00.00
BIOS 1.4.4

on centos7   i can login without any Issues to Restful with this Script.

But once using the centos8,......... it cannot.

When manual testing with "Talend API Tester"  the API itself works..

So feels something differs between centos7+centos8 when it comes to Rest handlings.

which issue this can be?

**Comment by bb-Ricardo** [comment]
Hi,

not that i know of. Are you still on CentOS 8 or CentOS Stream? Did you get an error message? Can you run the plugin with `-v` and post the whole output here?

Thank you

**Comment by madmax01** [comment]
ah the -v was the Hint.. didn't recognized that this Option is available.

Problem is it tries to hit an Proxy for the Local IP... and i'am not sure how to tell check_redfish.py  to avoid proxy Connection.  

is there an Option i can Use no_proxy or so?

**Comment by bb-Ricardo** [comment]
It uses the default urrlib3 python lib. You can control it via env vars: https://superuser.com/questions/196166/linux-command-line-to-turn-off-proxy

Just check your env via `set | grep -i proxy`. Then use `unset` to delete this vars from your environment und run the plugin again.

**Comment by dan-m-joh** [comment]
It (the proxy settings) probably get set in some script in /etc/profile.d or in your default .profile or .bashrc
I would add something like this in at the beginning of the "/etc/profile.d script":
```
# Skip all for noninteractive shells.
[ ! -t 0 ] && return
```
and if you have it in your .profile/.bashrc I would try something like
```
if [ -t 0 ]
then
    export HTTP_PROXY=...
fi
```

**Comment by madmax01** [comment]
i removed the entries which i had inside profile and profile.d  and works now.. not sure why but works..... thx guys ;). will close
