### ISSUE TITLE
Request error: No array controller data returned

### ISSUE THREAD

**Issue by ajoergensen** [bb-Ricardo/check_redfish#87]
Using check_redfish has worked for ages for monitoring our HPE Proliant servers, however we just got a couple of new ones which uses a different RAID controller than the others, now check_redfish fails with this message:

```
[UNKNOWN]: Request error: No array controller data returned for API URL '/redfish/v1/Systems/1//SmartStorage/ArrayControllers?$expand=.'
```
```
Server: HPE Proliant DL365 Gen10 Plus
ILO5 firmware: 2.65
Controller: SmartArray MR416i-a
Logical volume configured: RAID1 with two SSD
```

We have other DL365 Gen10 Plus which works as expected but they are equipped with SmartArray P408i

Mockup is available.

**Comment by ajoergensen** [comment]
Mockup sent.

**Comment by bb-Ricardo** [comment]
Hi,

thank you for the MockUp. I pushed a new 'next-release' commit to improve detection of Storage components on newer HPE systems.

can you try it out?

**Comment by ajoergensen** [comment]
Looks good

```
[OK]: Storage controller HPE MR416i-a Gen10+ Slot 12 (FW: 52.16.3-3913) status is: OK
[OK]: Physical Drive 240GB 6G SATA SSD Port=2I:Box=1:Bay=2 (VK000240GXAWE / SSD / SATA) 240.06GiB status: OK
[OK]: Physical Drive 240GB 6G SATA SSD Port=2I:Box=1:Bay=1 (VK000240GXAWE / SSD / SATA) 240.06GiB status: OK
[OK]: Logical Drive MR Volume (MR Volume) 240GiB (RAID1) status: OK
```
Thank you.

**Comment by bb-Ricardo** [comment]
great
