### ISSUE TITLE
Should this read vars.redfish_warning?

### ISSUE THREAD

**Issue by dorkmaneuver** [bb-Ricardo/check_redfish#92]
https://github.com/bb-Ricardo/check_redfish/blob/e55dd688e614a6e93abc361de171ff309cef8dee/contrib/icinga2_hw_service_checks_example.conf#L73

Maybe the lines 73 an 72 should read
        vars.redfish_warning = 3
        vars.redfish_critical = 1
Or this must be changed in the command.conf in order to work. But putting vars.redfish_... would follow the general conventions of Icinga and this plugin. 

Thanks so much for your excellent work! Highly appreciated and happy to contribute a little bit. :)

Cheers!

**Comment by bb-Ricardo** [comment]
Hi,

thank you for this hint. Indeed it is wrong and I just pushed a fix to `next-release` branch.
